export enum Paths {
  HOME = '/',
  ABOUT = '/about',
  MENTORS = '/',
  PRICING = '/pricing',
  MENTORPROFILE = '/mentor',
  BLOG = '/blog',
  FAQ = '/#faq',
  CONTACT = '/contact',
  POLICY = '/policy',
  TERMS = '/terms',
  FACEBOOK = '/',
  INSTAGRAM = '/',
  LINKEDIN = '/',
  YOUTUBE = '/',
  LOGIN = 'https://test.skillgu.com/auth/login',
  LOGINASMENTEE = '/',
  REGISTER = 'https://test.skillgu.com/register-mentor',
  REGISTERASMENTEE = '/',
  MENTORLIST = 'https://test.skillgu.com/search-mentors',
}
