export enum Paths {
  HOME = '/',
  ABOUT = '/about',
  MENTORS = '/',
  MENTORPROFILE = '/mentor',
  BLOG = '/blog',
  FAQ = '/#faq',
  CONTACT = '/contact',
  POLICY = '/policy',
  TERMS = '/terms',
  FACEBOOK = '/',
  INSTAGRAM = '/',
  LINKEDIN = '/',
  YOUTUBE = '/',
  LOGIN = '/',
  LOGINASMENTEE = '/',
  REGISTER = '/',
  REGISTERASMENTEE = '/',
}
