export enum Paths {
  HOME = '/',
  ABOUT = '/about',
  MENTORS = 'https://api.skillgu.com/search-mentors',
  FORMENTORS = '/mentors',
  FORMENTEE = '/mentee',
  PRICING = '/pricing',
  MENTORPROFILE = 'https://api.skillgu.com/mentor',
  BLOG = '/blog',
  FAQ = '/#faq',
  CONTACT = '/contact',
  POLICY = '/policy',
  TERMS = '/terms',
  FACEBOOK = '/',
  INSTAGRAM = '/',
  LINKEDIN = '/',
  YOUTUBE = '/',
  LOGIN = 'https://api.skillgu.com/auth/login',
  LOGINASMENTEE = 'https://api.skillgu.com/auth/login#mentee',
  REGISTER = 'https://api.skillgu.com/register-mentor',
  REGISTERASMENTEE = 'https://api.skillgu.com/register-mentee',
}
